/**
 * Generated by orval v8.0.0-rc.1 🍺
 * Do not edit manually.
 * WeMaster API - Generated Spec
 * Auto-generated OpenAPI specification from current NestJS implementation
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AuthResponseDto,
  LoginDto,
  RefreshTokenDto,
  RegisterDto
} from '../weMasterAPIGeneratedSpec.schemas';




  export const getAuth = () => {
/**
 * @summary Login with email and password
 */
const authControllerLogin = <TData = AxiosResponse<AuthResponseDto>>(
    loginDto: LoginDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/auth/login`,
      loginDto,options
    );
  }
/**
 * @summary Register a new user
 */
const authControllerRegister = <TData = AxiosResponse<AuthResponseDto>>(
    registerDto: RegisterDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/auth/register`,
      registerDto,options
    );
  }
/**
 * @summary Refresh access token
 */
const authControllerRefreshToken = <TData = AxiosResponse<void>>(
    refreshTokenDto: RefreshTokenDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/auth/refresh`,
      refreshTokenDto,options
    );
  }
return {authControllerLogin,authControllerRegister,authControllerRefreshToken}};
export type AuthControllerLoginResult = AxiosResponse<AuthResponseDto>
export type AuthControllerRegisterResult = AxiosResponse<AuthResponseDto>
export type AuthControllerRefreshTokenResult = AxiosResponse<void>
