/**
 * Generated by orval v8.0.0-rc.1 🍺
 * Do not edit manually.
 * WeMaster API - Generated Spec
 * Auto-generated OpenAPI specification from current NestJS implementation
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateDraftOrderResponseDto,
  CreateOrderDto,
  OrderResponseDto
} from '../weMasterAPIGeneratedSpec.schemas';




  export const getOrders = () => {
/**
 * @summary Create draft order and get checkout URL
 */
const ordersControllerCreateDraft = <TData = AxiosResponse<CreateDraftOrderResponseDto>>(
    createOrderDto: CreateOrderDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/orders/draft`,
      createOrderDto,options
    );
  }
/**
 * @summary Get order by ID
 */
const ordersControllerGetOrder = <TData = AxiosResponse<OrderResponseDto>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/orders/${id}`,options
    );
  }
return {ordersControllerCreateDraft,ordersControllerGetOrder}};
export type OrdersControllerCreateDraftResult = AxiosResponse<CreateDraftOrderResponseDto>
export type OrdersControllerGetOrderResult = AxiosResponse<OrderResponseDto>
