/**
 * Generated by orval v8.0.0-rc.1 🍺
 * Do not edit manually.
 * WeMaster API - Generated Spec
 * Auto-generated OpenAPI specification from current NestJS implementation
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  WebhookResponseDto
} from '../weMasterAPIGeneratedSpec.schemas';




  export const getPayments = () => {
/**
 * @summary Handle Stripe webhook events (idempotent)
 */
const paymentsControllerStripeWebhook = <TData = AxiosResponse<WebhookResponseDto>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/payments/webhooks/stripe`,undefined,options
    );
  }
return {paymentsControllerStripeWebhook}};
export type PaymentsControllerStripeWebhookResult = AxiosResponse<WebhookResponseDto>
