/**
 * Generated by orval v8.0.0-rc.1 🍺
 * Do not edit manually.
 * WeMaster API - Generated Spec
 * Auto-generated OpenAPI specification from current NestJS implementation
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateOfferingDto,
  OfferingResponseDto,
  OfferingsControllerList200,
  OfferingsControllerListParams
} from '../weMasterAPIGeneratedSpec.schemas';




  export const getOfferings = () => {
/**
 * @summary Create a new offering
 */
const offeringsControllerCreate = <TData = AxiosResponse<OfferingResponseDto>>(
    createOfferingDto: CreateOfferingDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/offerings`,
      createOfferingDto,options
    );
  }
/**
 * @summary List offerings with filters and pagination
 */
const offeringsControllerList = <TData = AxiosResponse<OfferingsControllerList200>>(
    params?: OfferingsControllerListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/offerings`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * @summary Get offering by slug
 */
const offeringsControllerFindBySlug = <TData = AxiosResponse<OfferingResponseDto>>(
    slug: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/offerings/${slug}`,options
    );
  }
return {offeringsControllerCreate,offeringsControllerList,offeringsControllerFindBySlug}};
export type OfferingsControllerCreateResult = AxiosResponse<OfferingResponseDto>
export type OfferingsControllerListResult = AxiosResponse<OfferingsControllerList200>
export type OfferingsControllerFindBySlugResult = AxiosResponse<OfferingResponseDto>
