/**
 * Generated by orval v8.0.0-rc.1 🍺
 * Do not edit manually.
 * WeMaster API - Generated Spec
 * Auto-generated OpenAPI specification from current NestJS implementation
 * OpenAPI spec version: 1.0.0
 */
export interface LoginDto {
  email: string;
  /** @minLength 6 */
  password: string;
}

export type AuthResponseDtoUser = { [key: string]: unknown };

export interface AuthResponseDto {
  accessToken: string;
  refreshToken: string;
  user: AuthResponseDtoUser;
}

export type RegisterDtoRole = typeof RegisterDtoRole[keyof typeof RegisterDtoRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RegisterDtoRole = {
  STUDENT: 'STUDENT',
  TUTOR: 'TUTOR',
  ADMIN: 'ADMIN',
} as const;

export interface RegisterDto {
  email: string;
  /** @minLength 6 */
  password: string;
  name?: string;
  role: RegisterDtoRole;
}

export interface RefreshTokenDto {
  refreshToken: string;
}

/**
 * Offering type
 */
export type CreateOfferingDtoType = typeof CreateOfferingDtoType[keyof typeof CreateOfferingDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateOfferingDtoType = {
  RECORDED: 'RECORDED',
  ONE_ON_ONE: 'ONE_ON_ONE',
  GROUP: 'GROUP',
  TRIAL: 'TRIAL',
} as const;

export interface CreateOfferingDto {
  /** Offering type */
  type: CreateOfferingDtoType;
  /** Offering title (1-200 chars) */
  title: string;
  /** URL-friendly slug */
  slug: string;
  /** Short summary */
  summary?: string;
  /** Full description (markdown supported) */
  description?: string;
  /** Thumbnail URL */
  thumbnail?: string;
  /** Category UUID */
  categoryId?: string;
  /** Tags array */
  tags?: string[];
  /** Pricing variants */
  variants: VariantDto[];
  /** Public visibility */
  isActive?: boolean;
}

export type OfferingResponseDtoType = typeof OfferingResponseDtoType[keyof typeof OfferingResponseDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OfferingResponseDtoType = {
  RECORDED: 'RECORDED',
  ONE_ON_ONE: 'ONE_ON_ONE',
  GROUP: 'GROUP',
  TRIAL: 'TRIAL',
} as const;

export interface OfferingResponseDto {
  id: string;
  type: OfferingResponseDtoType;
  title: string;
  slug: string;
  summary?: string;
  description?: string;
  thumbnail?: string;
  categoryId?: string;
  tags?: string[];
  variants: VariantDto[];
  isActive: boolean;
  tutorId: string;
  tenantId: string;
  createdAt: string;
  updatedAt: string;
}

export interface CreateOrderDto {
  /** Order items (min: 1) */
  items: OrderItemDto[];
}

export interface CreateDraftOrderResponseDto {
  orderId: string;
  /** Stripe checkout URL */
  checkoutUrl: string;
  /** Order amount in cents */
  amount: number;
  currency: string;
}

export type OrderResponseDtoStatus = typeof OrderResponseDtoStatus[keyof typeof OrderResponseDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderResponseDtoStatus = {
  DRAFT: 'DRAFT',
  PENDING_PAYMENT: 'PENDING_PAYMENT',
  PAID: 'PAID',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED',
} as const;

export interface OrderResponseDto {
  id: string;
  userId: string;
  tenantId: string;
  status: OrderResponseDtoStatus;
  /** Total amount in cents */
  amount: number;
  currency: string;
  /** Stripe checkout URL */
  checkoutUrl?: string;
  /** Stripe session ID */
  stripeSessionId?: string;
  items: OrderItemResponseDto[];
  createdAt: string;
  updatedAt: string;
}

export interface WebhookResponseDto {
  /** Whether webhook was received */
  received: boolean;
  /** Whether event was already processed */
  alreadyProcessed?: boolean;
}

export type OfferingsControllerListParams = {
/**
 * Page number (min: 1)
 */
page?: number;
/**
 * Items per page (1-100)
 */
limit?: number;
/**
 * Filter by type
 */
type?: OfferingsControllerListType;
/**
 * Filter by status
 */
status?: OfferingsControllerListStatus;
};

export type OfferingsControllerListType = typeof OfferingsControllerListType[keyof typeof OfferingsControllerListType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OfferingsControllerListType = {
  RECORDED: 'RECORDED',
  ONE_ON_ONE: 'ONE_ON_ONE',
  GROUP: 'GROUP',
  TRIAL: 'TRIAL',
} as const;

export type OfferingsControllerListStatus = typeof OfferingsControllerListStatus[keyof typeof OfferingsControllerListStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OfferingsControllerListStatus = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  ARCHIVED: 'ARCHIVED',
} as const;

export type OfferingsControllerList200Pagination = {
  total?: number;
  page?: number;
  limit?: number;
  totalPages?: number;
};

export type OfferingsControllerList200 = {
  items?: OfferingResponseDto[];
  pagination?: OfferingsControllerList200Pagination;
};

